version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s
    networks:
      - pinpoint-docker_pinpoint

  app:
    container_name: spring-boot-app
    build:
      context: .
      dockerfile: Dockerfile-pinpoint
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - PINPOINT_ENABLE=true
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "8080:8080"
    networks:
      - pinpoint-docker_pinpoint

networks:
  pinpoint-docker_pinpoint:
    external: true
