version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s
    networks:
      - app-network

  app:
    container_name: spring-boot-app
    build:
      context: .
      dockerfile: Dockerfile
    env_file: 
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - REDIS_HOST=redis  # Docker Compose 내에서 Redis 컨테이너 이름으로 설정
      - REDIS_PORT=6379   # Redis 기본 포트
    ports:
      - "8080:8080"
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
